server:
  port: 8772

spring:
  application:
    name: sc-service-zipkin-client
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
