spring:
  application:
    name: service-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mr-Joke/sc-demo/tree/master/sc-service-config-server/
          search-paths: config
          username:
          password:
      label: master

server:
  port: 8767
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
